<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mas2g</string>
	</array>
	<key>name</key>
	<string>GOAL (mas)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(environment)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#environment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(agentfiles)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#agentfiles</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(launchpolicy)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#launchpolicy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>agentfiles</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((")[^"]*\.goal("))\s*\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.goal.mas</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.goal.mas</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]\s*\.</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>name</string>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.goal.mas</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(")[^"]*\.goal(")</string>
					<key>name</key>
					<string>string.quoted.double.goal.mas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.goal.mas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.goal.mas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((%).*)</string>
		</dict>
		<key>environment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.goal.mas</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.goal.mas</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(env)\s*=\s*((")[^"]*\.jar("))\s*\.</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(init)\s*=\s*\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]\s*\.</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#environment-parameters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>environment-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(-?[0-9]+\.?[0-9]*((e|E)-?[0-9]+)?|\.[0-9]+((e|E)-?[0-9]+)?)</string>
					<key>name</key>
					<string>constant.numeric.numeral.goal.mas</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#environment-parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>launchpolicy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(when)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(do)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#launchrule</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(launch)\s*(((\*)|([a-zA-Z_][a-zA-Z0-9_]*))(\s)*:(\s)*[a-zA-Z_][a-zA-Z0-9_]*)\s*\.</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>launchrule</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(type|max|name)</string>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(entity|@env)</string>
					<key>name</key>
					<string>support.class.goal.mas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.goal.mas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.goal.mas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(")[^"]+(")</string>
			<key>name</key>
			<string>string.quoted.double.goal.mas</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.goal.mas</string>
	<key>uuid</key>
	<string>8cf6ac10-61cb-48d9-8dd4-c15f64f15996</string>
</dict>
</plist>
