<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>goal</string>
	</array>
	<key>name</key>
	<string>GOAL (goal)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(main|event|init)\s+(module)\s*(?:\[.*\])?\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(module)\s+(?:[a-zA-Z_$][a-zA-Z0-9_$]*)(?:\([a-zA-Z0-9_$(),\s]+\))?\s*(?:\[.*\])?\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.goal.mas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>action-rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#(define)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.define.goal.goal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.preprocessor.goal.goal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\.\s*\n</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ms-query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(if)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(then)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ms-query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(forall)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(do)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ms-query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(listall)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(do)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#listall-conditions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(adopt|drop|insert|delete|send|sendonce)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s(exit-module)(:?\(all\))?</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>action-spec</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z\$_][a-zA-Z0-9_\$]+)\s*(?:(\()\s*([A-Z][a-zA-Z0-9_]*(?:\s*,\s*[A-Z][a-zA-Z0-9_]*)*)\s*(\)))?\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.goal.goal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.goal.goal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.goal.goal</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.goal.goal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-spec-prepost</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>action-spec-prepost</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(pre|post)\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.goal.mas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.goal.mas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((%).*)</string>
		</dict>
		<key>listall-conditions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(not)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ms-query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(a-goal|goal|goal-a|bel|[a-zA-Z\$_][a-zA-Z0-9_\$]+)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(true)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>module</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(knowledge|beliefs|goals)\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(program)\s*(?:\[.*\])?\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-rules</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(actionspec)\s*(?:\[.*\])?\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-spec</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ms-query</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(not)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ms-query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(a-goal|goal|goal-a|bel)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string></string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.goal.mas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(true)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.goal.mas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.goal.mas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(")[^"]+(")</string>
			<key>name</key>
			<string>string.quoted.double.goal.mas</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.goal.goal</string>
	<key>uuid</key>
	<string>4aa68f0f-a1cd-4041-ac63-17bf0e6e60a1</string>
</dict>
</plist>
